title: File Browser
email: hacdias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  File Browser is a stylish and elegant web file manager you can use
  as your own cloud or integrate on your own applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filebrowser.github.io"
twitter_username: hacdias
github_username:  filebrowser
google_analytics: UA-114347250-1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

docs:
  - page: Quick Start
    url: /quick-start/
  - page: Installation
    url: /installation/
    links:
      - page: One-step Script
        url: /installation/#one-step-script
      - page: Caddy
        url: /installation/#caddy
      - page: Docker
        url: /installation/#docker
  - page: Configuration
    url: /configuration/
    links:
      - page: Flags
        url: /configuration/#flags
      - page: Available locales
        url: /configuration/#available-locales
      - page: Configuration file
        url: /configuration/#configuration-file
  - page: Caddy Plugins
    url: /caddy/
